config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:'skills#index'
  resources :skills, only: [:index, :update] do
    collection do
      get 'study'
      get 'test'
      get 'test2'
      get 'rank'
      get 'preposition'
      get 'exp_preposition'
      get 'preposition_img'
      get 'opposite'
      get 'test3'
      get 'opposite_sheet'
      get 'similar'
      get 'similar_problem'
      get 'similar_sheet'
      get 'unexpect'
      get 'unexpect_sheet'
    end
  end
  resources :users, only: :show
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 6 }
  validates :pre_score, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 18 }
  validates :input_words, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 24 }   
  validates :preposition_score, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 24 }   
  validates :unexp_score, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 46 }   
  validates :similar_score, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 40 }   

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
      user.name = "ゲスト"
      user.pre_score = 0
      user.input_words = 0
      user.preposition_score = 0
      user.unexp_score = 0
      user.similar_score = 0
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:name, :pre_score, :input_words, :preposition_score, :unexp_score, :similar_score])
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authenticate_user!, only: [:test, :test2, :preposition, :test3, :similar_problem]
  def index
  end

  def study
  end

  def test
    @user = User.new
  end

  def test2
  end

  def test3
  end

  def similar_problem
  end

  def update
    @user = User.find(params[:id])
    @user.update(pre_score_params)
    @user.update(input_words_params)
    @user.update(preposition_score_params)
    @user.update(unexp_score_params)
    @user.update(similar_score_params)
    unless @user.valid?
      redirect_to root_path
      flash[:notice] = "得点が保存できませんでした"
    end
  end

  def rank
    @users = User.all.order(pre_score: :DESC).limit(3)
    @verb_users = User.all.order(input_words: :DESC).limit(3)
    @preposition_users = User.all.order(preposition_score: :DESC).limit(3)
    @unexp_users = User.all.order(unexp_score: :DESC).limit(3)
    @similar_users = User.all.order(similar_score: :DESC).limit(3)
  end

  # def preposition
  # end

  # def exp_preposition
  # end

  def preposition_img
  end

  
  

  private
  def pre_score_params
    params.permit(:pre_score)
  end
   
  def input_words_params
    params.permit(:input_words)
  end

  def preposition_score_params
    params.permit(:preposition_score)
  end

  def unexp_score_params
    params.permit(:unexp_score)
  end
  def similar_score_params
    params.permit(:similar_score)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skillup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
    
  </body>
</html>

app/views/skills/exp_preposition.html.erb
<div class="upper-content">
  <%= link_to('トップページに戻る',root_path,class:"top-btn") %>
</div>
<div class="upper-explain-btn">
  <div id="prev-preposition">前へ</div>
  <div id ="insert-preposition-area">onを見て思い浮かべること</div>
  <div id="next-preposition">次へ</div>
</div>
<p class="small-comment">（大体のニュアンスが合っていればオッケー）</p>
<div id="exp-preposition" class="hidden">
</div>
<div id="change-btn">説明を見る</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('#change-btn').click(function(){
      if($('#exp-preposition').hasClass('hidden')){
        $('#exp-preposition').removeClass('hidden')
        $('#change-btn').text('説明を隠す')
      } else {
        $('#exp-preposition').addClass('hidden')
        $('#change-btn').text('説明を見る')
      }
    })
  });
</script>

app/views/skills/opposite.html.erb
<div class="upper-content">
  <%= link_to('トップページに戻る',root_path,class:"top-btn") %>
</div>
<h1 class="opposite-lists-title">反対語を覚えるとある良い効果の例</h1>
<div class="points">
  <ul class="point-lists">
    <li class="point-list">複数の文章の英文を読んだ時に、文章の対応関係が把握しやすくなる</li>
    <li class="point-list">1の例として逆説、対比などがわかりやすくなる</li>
    <li class="point-list">長文問題などで逆説、対比を見つけることができれば空所補充問題の正解率を上げることができる</li>
    <li class="point-list">3のことが文法問題でも起こる</li>
  </ul>
</div>
<h1 class="opposite-lists-title" id="noun">反対語一覧（名詞）</h1>
<table>
  <tr>
    <td>可能性</td>
    <td>posibility</td>
    <td> impossibility</td>
    <td>不可能性</td>
  </tr>
  <tr>
    <td>敬意</td>
    <td>respect</td>
    <td>disrespect</td>
    <td>無礼</td>
  </tr>
  <tr>
    <td>雇い主</td>
    <td>employer</td>
    <td>employee</td>
    <td>従業員</td>
  </tr>
  <tr>
    <td>正確さ</td>
    <td>accuracy</td>
    <td>inaccuracy</td>
    <td>不正確さ</td>
  </tr>
  <tr>
    <td>適正</td>
    <td>competence</td>
    <td>incompetence</td>
    <td>不適正</td>
  </tr>
  <tr>
    <td>増加</td>
    <td>increase</td>
    <td>decrease</td>
    <td>データ</td>
  </tr>
  <tr>
    <td>債権者</td>
    <td>creditor</td>
    <td>debtor</td>
    <td>債務者</td>
  </tr>
  <tr>
    <td>利益</td>
    <td>gain</td>
    <td>loss</td>
    <td>損失</td>
  </tr>
  <tr>
    <td>小売り</td>
    <td>retail</td>
    <td>wholesale</td>
    <td>卸売り</td>
  </tr>
  <tr>
    <td>黒字</td>
    <td>surplus</td>
    <td>deflict</td>
    <td>赤字</td>
  </tr>
  <tr>
    <td>原因</td>
    <td>cause</td>
    <td>effect</td>
    <td>結果</td>
  </tr>
  <tr>
    <td>家主</td>
    <td>landlord</td>
    <td>tenant</td>
    <td>借家人、借土人</td>
  </tr>
  <tr>
    <td>近道</td>
    <td>shortcut</td>
    <td>detour</td>
    <td>迂回路</td>
  </tr>
  <tr>
    <td>楽観主義</td>
    <td>optimism</td>
    <td>pessimism</td>
    <td>悲観主義</td>
  </tr>
  <tr>
    <td>支持者</td>
    <td>proponent</td>
    <td>opponent</td>
    <td>反対者</td>
  </tr>
  <tr>
    <td>重要</td>
    <td>demand</td>
    <td>supply</td>
    <td>供給</td>
  </tr>
  <tr>
    <td>出席</td>
    <td>presence</td>
    <td>absence</td>
    <td>欠席</td>
  </tr>
  <tr>
    <td>共感</td>
    <td>sympathy</td>
    <td>antipathy</td>
    <td>反感</td>
  </tr>
  <tr>
    <td>拒否</td>
    <td>rejection</td>
    <td>acceptance</td>
    <td>受け入れ</td>
  </tr>
  <tr>
    <td>吸い込み口</td>
    <td>intake</td>
    <td>outlet</td>
    <td>排出口</td>
  </tr>
  <tr>
    <td>祖先</td>
    <td>ancestor</td>
    <td>descendant</td>
    <td>子孫</td>
  </tr>
  <tr>
    <td>収入</td>
    <td>income</td>
    <td>outgo, expenses</td>
    <td>支出</td>
  </tr>
  <tr>
    <td>優越</td>
    <td>superiority</td>
    <td>inferiority</td>
    <td>劣等</td>
  </tr>
  <tr>
    <td>最大</td>
    <td>maximum</td>
    <td>minimum</td>
    <td>最小</td>
  </tr>
  <tr>
    <td>量</td>
    <td>quantity</td>
    <td>quality</td>
    <td>質</td>
  </tr>
  <tr>
    <td>多数派</td>
    <td>majority</td>
    <td>minority</td>
    <td>少数派</td>
  </tr>
  <tr>
    <td>入り口</td>
    <td>entrance</td>
    <td>exit</td>
    <td>出口</td>
  </tr>
  <tr>
    <td>よい面、上側</td>
    <td>upside</td>
    <td>downside</td>
    <td>悪い面、下側</td>
  </tr>
  <tr>
    <td>容易さ</td>
    <td>ease</td>
    <td>difficulty</td>
    <td>難しさ</td>
  </tr>
  <tr>
    <td>忠義、忠実、誠実</td>
    <td>loyalty</td>
    <td>disloyalty</td>
    <td>不忠実、不誠実</td>
  </tr>
  <tr>
    <td>下落</td>
    <td>downturn</td>
    <td>upturn</td>
    <td>好転</td>
  </tr>
  <tr>
    <td>部下</td>
    <td>subordinate</td>
    <td>superior, boss</td>
    <td>上司</td>
  </tr>
</table>
<h1 class="opposite-lists-title" id="adjective">反対語一覧（形容詞）</h1>
<table>
  <tr>
    <td>往復の</td>
    <td>round-trip</td>
    <td>one-way</td>
    <td>片道の</td>
  </tr>
  <tr>
    <td>予想可能な</td>
    <td>predictable</td>
    <td>unpredictable</td>
    <td>予想不可能な</td>
  </tr>
  <tr>
    <td>無責任な</td>
    <td>irreponsible</td>
    <td>responsive</td>
    <td>責任のある</td>
  </tr>
  <tr>
    <td>能動的な</td>
    <td>active</td>
    <td>passive</td>
    <td>受動的な</td>
  </tr>
  <tr>
    <td>田舎の</td>
    <td>rural</td>
    <td>urban</td>
    <td>都会の</td>
  </tr>
  <tr>
    <td>数えられる</td>
    <td>numerable</td>
    <td>innumerable</td>
    <td>数え切れない</td>
  </tr>
  <tr>
    <td>自発的な</td>
    <td>voluntary</td>
    <td>compulsory / mandatory / obligatory</td>
    <td>強制的な</td>
  </tr>
  <tr>
    <td>素人の</td>
    <td>amateur</td>
    <td>professional</td>
    <td>専門家の</td>
  </tr>
  <tr>
    <td>熟した</td>
    <td>mature</td>
    <td>immature</td>
    <td>未熟な</td>
  </tr>
  <tr>
    <td>有形の</td>
    <td>tangible</td>
    <td>intangible</td>
    <td>無形の</td>
  </tr>
  <tr>
    <td>十分な</td>
    <td>adequate</td>
    <td>inadequate</td>
    <td>不十分な</td>
  </tr>
  <tr>
    <td>敬意</td>
    <td>respect</td>
    <td>disrespect</td>
    <td>無礼</td>
  </tr>
  <tr>
    <td>抽象的な</td>
    <td>abstract</td>
    <td>concrete</td>
    <td>具体的な</td>
  </tr>
  <tr>
    <td>礼儀正しい意</td>
    <td>polite</td>
    <td>rude</td>
    <td>失礼な</td>
  </tr>
  <tr>
    <td>確かな</td>
    <td>certain</td>
    <td>uncertain</td>
    <td>不確かな</td>
  </tr>
  <tr>
    <td>定期的な</td>
    <td>regular</td>
    <td>irregular</td>
    <td>不定期な</td>
  </tr>
  <tr>
    <td>食用の</td>
    <td>edible</td>
    <td>inedible</td>
    <td>食用でない</td>
  </tr>
  <tr>
    <td>垂直の</td>
    <td>upright</td>
    <td>horizontal</td>
    <td>水平の</td>
  </tr>
  <tr>
    <td>本物の</td>
    <td>authentic</td>
    <td>fake</td>
    <td>偽物の</td>
  </tr>
  <tr>
    <td>人手不足の</td>
    <td>understaffed</td>
    <td>overstaffed</td>
    <td>人員過剰の</td>
  </tr>
  <tr>
    <td>無関係の</td>
    <td>irrelevant</td>
    <td>relevant</td>
    <td>関係のある</td>
  </tr>
  <tr>
    <td>入手可能な</td>
    <td>available</td>
    <td>unavailable</td>
    <td>入手不可能な</td>
  </tr>
  <tr>
    <td>使用中の</td>
    <td>occupied</td>
    <td>unoccupied</td>
    <td>使用されていない</td>
  </tr>
  <tr>
    <td>後者の</td>
    <td>latter</td>
    <td>former</td>
    <td>前者の</td>
  </tr>
  <tr>
    <td>慢性の</td>
    <td>chronic</td>
    <td>acute</td>
    <td>急性の</td>
  </tr>
  <tr>
    <td>貧乏な</td>
    <td>poor</td>
    <td>affluent / rich / wealthy</td>
    <td>豊かな</td>
  </tr>
  <tr>
    <td>思いやりのある</td>
    <td>considerate</td>
    <td>inconsiderate</td>
    <td>思いやりのない</td>
  </tr>
  <tr>
    <td>決定的な</td>
    <td>conclusive</td>
    <td>inconclusive</td>
    <td>決定的でない</td>
  </tr>
  <tr>
    <td>目立つ</td>
    <td>conspicuous</td>
    <td>inconspicuous</td>
    <td>目立たない</td>
  </tr>
  <tr>
    <td>活況の</td>
    <td>brisk</td>
    <td>stagnant / sluggish</td>
    <td>停滞した</td>
  </tr>
  <tr>
    <td>明確な</td>
    <td>clear</td>
    <td>obscure, unclear</td>
    <td>曖昧な</td>
  </tr>
  <tr>
    <td>合理的な</td>
    <td>rational</td>
    <td>irrational</td>
    <td>非合理的な</td>
  </tr>
  <tr>
    <td>言葉による</td>
    <td>verbal, oral </td>
    <td>written</td>
    <td>文章による</td>
  </tr>
  <tr>
    <td>偏った</td>
    <td>biased</td>
    <td>unbiased</td>
    <td>偏見のない</td>
  </tr>
  <tr>
    <td>安定した</td>
    <td>stable</td>
    <td>unstable</td>
    <td>不安定な</td>
  </tr>
  <tr>
    <td>含んだ</td>
    <td>inclusive</td>
    <td>exclusive</td>
    <td>排除した</td>
  </tr>
  <tr>
    <td>倫理的な</td>
    <td>ethical</td>
    <td>unethical</td>
    <td>非倫理的な</td>
  </tr>
  <tr>
    <td>勤勉な</td>
    <td>diligent / industrious</td>
    <td>idle / lazy</td>
    <td>怠惰な</td>
  </tr>
  <tr>
    <td>最小の</td>
    <td>minimal</td>
    <td>maximal</td>
    <td>最大の</td>
  </tr>
  <tr>
    <td>時代遅れの</td>
    <td>outdated</td>
    <td>fashionable</td>
    <td>流行の</td>
  </tr>
</table>  

app/views/skills/preposition.html.erb
<div class="upper-content">
  <%= link_to('トップページに戻る',root_path,class:"top-btn") %>
</div>
<div class="title-2">
  前置詞テスト
</div>

<div class="preposition-area">
  <p id ="ask-preposition"></p>
  <input type="text" id ="preposition">
  <button id="preposition-button">OK</button>
</div>
<p class="preposition-text">問題文に合うニュアンスの前置詞を記述しよう</p>
<div id="preposition-answer-modal" class="hidden">
  <p id="preposition-answer"></p>
</div>
<div id="form" class="hidden" >
    <%= form_with(url: skill_path(current_user.id),local: true,class:"score-form",method: :put) do |f| %>
      <div id = "correct-preposition-area"></div>
      <%= f.number_field :preposition_score, autofocus: true,class:"input-default",id:"pre-score" %>
      <%= f.submit "得点を記録する",class:"preposition-score-btn" %>
      <% end %> 
    <%= link_to 'もう一度行う',preposition_skills_path,class:"preposition-once-btn" %> 
  </div>
</div>

app/views/skills/similar.html.erb
<div class="upper-content">
  <%= link_to('トップページに戻る',root_path,class:"top-btn") %>
</div>
<h1 class="similar-lists-title">類義語を覚えるとある良い効果の例</h1>
<div class="points">
  <ul class="point-lists">
    <li class="point-list">効率的に単語を覚えることができる</li>
    <li class="point-list">文法問題の正解率が上がる</li>
    <li class="point-list">複数の文章の英文を読んだ時に、言い換えの表現がわかる</li>
    <li class="point-list">1の例として、長文問題の空所問題で別の部分と言い換えていることがわかればそこの部分の対応する単語、または文章を入れれば良い。ということがわかるようになる。</li>
  </ul>
</div>
<h1 class="similar-lists-title" >類義語一覧（名詞）</h1>
<table>
  <tr>
    <td>顧客</td>
    <td>customer</td>
    <td>client</td>
  </tr>
  <tr>
    <td>答え</td>
    <td>answer</td>
    <td>reply</td>
  </tr>
  <tr>
    <td>機会</td>
    <td>chance</td>
    <td>opportunity</td>
  </tr>
  <tr>
    <td>展示会</td>
    <td>exhibition</td>
    <td>fair</td>
  </tr>
  <tr>
    <td>臭い</td>
    <td>odor</td>
    <td>smell</td>
  </tr>
  <tr>
    <td>所持品</td>
    <td>belongings</td>
    <td>possessions</td>
  </tr>
  <tr>
    <td>会議</td>
    <td>convention</td>
    <td>congress</td>
  </tr>
  <tr>
    <td>請求書</td>
    <td>invoice</td>
    <td>bill</td>
  </tr>
  <tr>
    <td>予約</td>
    <td>reservation</td>
    <td>booking</td>
  </tr>
  <tr>
    <td>証拠</td>
    <td>evidence</td>
    <td>proof</td>
  </tr>
  <tr>
    <td>職</td>
    <td>position</td>
    <td>post</td>
  </tr>
  <tr>
    <td>進歩</td>
    <td>progress</td>
    <td>advance</td>
  </tr>
  <tr>
    <td>草稿</td>
    <td>draft</td>
    <td>manuscript</td>
  </tr>
  <tr>
    <td>援助</td>
    <td>help</td>
    <td>aid</td>
  </tr>
  <tr>
    <td>料理</td>
    <td>cuisine</td>
    <td>cooking</td>
  </tr>
  <tr>
    <td>引用</td>
    <td>excerpt</td>
    <td>extract</td>
  </tr>
  <tr>
    <td>素早さ</td>
    <td>promptness</td>
    <td>speed</td>
  </tr>
  <tr>
    <td>努力</td>
    <td>effort</td>
    <td>endeavor</td>
  </tr>
  <tr>
    <td>成功</td>
    <td>achievement</td>
    <td>success</td>
  </tr>
  <tr>
    <td>通信</td>
    <td>correspondence</td>
    <td>communication</td>
  </tr>
  <tr>
    <td>混乱</td>
    <td>disorder</td>
    <td>confusion</td>
  </tr>
  <tr>
    <td>通路</td>
    <td>hallway</td>
    <td>corridor</td>
  </tr>
  <tr>
    <td>趣味</td>
    <td>pastime</td>
    <td>hobby</td>
  </tr>
  <tr>
    <td>地域</td>
    <td>area</td>
    <td>region</td>
  </tr>
  <tr>
    <td>動機</td>
    <td>incentive</td>
    <td>motivation</td>
  </tr>
  <tr>
    <td>制約</td>
    <td>constrain</td>
    <td>restriction</td>
  </tr>
  <tr>
    <td>評価</td>
    <td>appraisal</td>
    <td>assessment, evaluation</td>
  </tr>
  <tr>
    <td>合間、休止</td>
    <td>intermission</td>
    <td>pause, break</td>
  </tr>
  <tr>
    <td>正確さ</td>
    <td>accuracy</td>
    <td>precision</td>
  </tr>
  <tr>
    <td>報酬</td>
    <td>reward</td>
    <td>remuneration</td>
  </tr>
  <tr>
    <td>認可</td>
    <td>authorization</td>
    <td>permission</td>
  </tr>
  <tr>
    <td>控除</td>
    <td>exemption</td>
    <td>reduction</td>
  </tr>
  <tr>
    <td>健康</td>
    <td>fitness</td>
    <td>health</td>
  </tr>
  <tr>
    <td>暴露</td>
    <td>revelation</td>
    <td>disclosure</td>
  </tr>
  <tr>
    <td>責任</td>
    <td>liability</td>
    <td>responsibility</td>
  </tr>
  <tr>
    <td>企業買収</td>
    <td>takeover</td>
    <td>buyout</td>
  </tr>
  <tr>
    <td>称賛</td>
    <td>acclaim</td>
    <td>praise</td>
  </tr>
  <tr>
    <td>企業</td>
    <td>enterprise</td>
    <td>company</td>
  </tr>
  <tr>
    <td>商品</td>
    <td>merchandise</td>
    <td>goods</td>
  </tr>
  <tr>
    <td>小冊子</td>
    <td>brochure</td>
    <td>pamphlet, booklet</td>
  </tr>
</table>

app/views/skills/similar_problem.html.erb
<div class="upper-content">
  <%= link_to('トップページに戻る',root_path,class:"top-btn") %>
</div>
<div class="test-text">
  第<span id="testNum"></span>問
</div>
<div id="text-area">
  <div id="question-text">次の単語の類義語を選択してください</div>
    <div id ="sim-question"></div>
  <div class="choices-area">
    <ul id ="sim-choices">
    </ul>
  </div>
  <div id ="btn">次へ</div>
  <div id="form" class="hidden" >
    <%= form_with(url: skill_path(current_user.id),local: true,class:"score-form",method: :put) do |f| %>
      <div id = "score-area"></div>
      <%= f.number_field :similar_score, autofocus: true,class:"input-default",id:"pre-score" %>
      <%= f.submit "得点を記録する",class:"score-btn" %>
      <% end %> 
    <div id="time-record-area">タイム:<span id="time-record">00:00</span></div>  
    <%= link_to 'もう一度行う',test_skills_path,class:"once-btn" %> 
  </div>
</div>
<div id ="timer-area">経過時間：<span id="timer">00:00</span></div>

app/views/skills/study.html.erb
<div class="upper-content">
  <%= link_to('トップページに戻る',root_path,class:"top-btn") %>
</div>

<div class="contents">
  <p id ="problem-text"></p>  
  <div class="answer-btn"  id ="answer-btn">
    答えを見る
  </div>
</div>

<div class="under-contents">
  <div id ="prev">前へ</div>
  <div id="answer" class="hidden">
    
  </div>
  <div id ="next">次へ</div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('#answer-btn').click(function(){
      if($('#answer').hasClass('hidden')){
        $('#answer').removeClass('hidden')
        $('#answer-btn').text('答えを隠す')
      } else {
        $('#answer').addClass('hidden')
        $('#answer-btn').text('答えを見る')
      }
    })
  });
</script>

app/views/skills/test.html.erb
<div class="upper-content">
  <%= link_to('トップページに戻る',root_path,class:"top-btn") %>
</div>
<div class="test-text">
  第<span id="testNum"></span>問
</div>
<div id="text-area">
  <div id="question-text">次の単語の意味の場所を押してください</div>
    <div id ="question"></div>
  <div class="choices-area">
    <ul id ="choices">
    </ul>
  </div>
  <div id ="btn">次へ</div>
  <div id="form" class="hidden" >
    <%= form_with(url: skill_path(current_user.id),local: true,class:"score-form",method: :put) do |f| %>
      <div id = "score-area"></div>
      <%= f.number_field :pre_score, autofocus: true,class:"input-default",id:"pre-score" %>
      <%= f.submit "得点を記録する",class:"score-btn" %>
      <% end %> 
    <div id="time-record-area">タイム:<span id="time-record">00:00</span></div>  
    <%= link_to 'もう一度行う',test_skills_path,class:"once-btn" %> 
  </div>
</div>
<div id ="timer-area">経過時間：<span id="timer">00:00</span></div>

app/views/skills/test2.html.erb
<div class="upper-content">
  <%= link_to('トップページに戻る',root_path,class:"top-btn") %>
</div>
<div class="title-2">
  単語テスト
</div>

<div class="input-area">
  <p id ="ask-word"></p>
  <input type="text" id ="word">
  <button id="button">OK</button>
</div>
<p class="preposition-text">問題文に合う意味の基本動詞を記述しよう</p>
<div id="answer-modal" class="hidden">
  <p id="word-answer"></p>
</div>
<div id="form" class="hidden" >
    <%= form_with(url: skill_path(current_user.id),local: true,class:"score-form",method: :put) do |f| %>
      <div id = "correct-number-area"></div>
      <%= f.number_field :input_words, autofocus: true,class:"input-default",id:"pre-score" %>
      <%= f.submit "得点を記録する",class:"score-btn" %>
      <% end %> 
    <%= link_to 'もう一度行う',test2_skills_path,class:"once-btn" %> 
  </div>
</div>

app/views/skills/test3.html.erb
<div class="upper-content">
  <%= link_to('トップページに戻る',root_path,class:"top-btn") %>
</div>
<div class="test-text">
  第<span id="testNum"></span>問
</div>
<div id="text-area">
  <div id="question-text">次の単語の意味の場所を押してください</div>
    <div id ="une-question"></div>
  <div class="choices-area">
    <ul id ="une-choices">
    </ul>
  </div>
  <div id ="btn">次へ</div>
  <div id="form" class="hidden" >
    <%= form_with(url: skill_path(current_user.id),local: true,class:"score-form",method: :put) do |f| %>
      <div id = "score-area"></div>
      <%= f.number_field :unexp_score, autofocus: true,class:"input-default",id:"pre-score" %>
      <%= f.submit "得点を記録する",class:"score-btn" %>
      <% end %> 
    <div id="time-record-area">タイム:<span id="time-record">00:00</span></div>  
    <%= link_to 'もう一度行う',test_skills_path,class:"once-btn" %> 
  </div>
</div>
<div id ="timer-area">経過時間：<span id="timer">00:00</span></div>

app/views/skills/update.html.erb
<div class="upper-content">
  <%= link_to('トップページに戻る',root_path,class:"top-btn") %>
</div>
<div class="nill-class"></div>